services:
  mysql:
    image: mysql:8.0
    container_name: jaegokok-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jaegokok
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: jaegokok-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
