spring:
  config:
    activate:
      on-profile: "mail"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-gmail@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
