spring:
  application:
    name: jaegokok
  profiles:
    group:
      local: "local"
      dev: "dev"
      prod: "prod"
    include:
      - datasource
      - redis
      - security
      - docs

server:
  port: 8080
